fix: operation not permitted in self hosted runners
Self hosted runners in fedora make the docker.sock a link to /run/podman/podman.sock

Trying to set the :z on docker.sock seems to cause:
```
Error: lsetxattr /var/run/docker.sock: operation not permitted

Error: The process '/usr/bin/docker' failed with exit code 126
```
I think the :z may be broken for links?  hard to tell.